image:
  registry: ghcr.io
  repository: ionos-cloud/external-dns-webhook-provider
  tag: latest

provider: webhook

namespace: external-dns-ionoscore

domainFilters:
  - test-dns-public-0002.info

extraArgs:
  webhook-provider-url: http://localhost:8888

logLevel: debug
logFormat: json

sidecars:
  - name: ionos-webhook
    image: ghcr.io/ionos-cloud/external-dns-ionos-webhook:ionoscloud
    ports:
      - containerPort: 8888
        name: http
    livenessProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 10
      timeoutSeconds: 5
    env:
      - name: LOG_LEVEL
        value: debug
      - name: LOG_FORMAT
        value: json
      - name: IONOS_API_KEY
        valueFrom:
          secretKeyRef:
            name: ionos-credentials
            key: api-key
      - name: SERVER_HOST
        value: "0.0.0.0" 
#      - name: IONOS_DEBUG
#        value: "true"
      - name: DRY_RUN
        value: "false"
      - name: DOMAIN_FILTER
        value: "test-dns-public-0002.info"
