apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: external-dns-ionoscore
  labels:
    ionos.cloud/metrics: "true"
spec:
  podMetricsEndpoints:
    - port: http
      relabelings:
        - targetLabel: job
          replacement: external-dns-ionoscore
        - targetLabel: instance
          sourceLabels: [pod]
        - action: labelkeep
          regex: (job|instance|__.*)
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-dns-ionoscore
  namespaceSelector:
    any: false
    matchNames:
      - external-dns-ionoscore
